### ISSUE TITLE
The bitset doesn't return the 0s and 1s 

### ISSUE THREAD

**Issue by Agipa** [TheTannerRyan/ring#5]
Hello! Sorry for concerning, but can't understand why Marshal.Binary returns [1 0 0 0 0 0 0 3 191 0 0 0 0 0 0 0 7 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 32 0 0 0 0 0 0 0 0 32 0 0 128 16 0 0 0 0 0 0 0 36 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 16 0 0 0 0 0 0 0 4 0 0 0 64 0 0 0 0 0 0 16 0 64 4 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 4 0] <nil> this, fro where this numbers "191, 3,36, ...", Bloom Filter isn't bitset which should give "101010101" this type of bitset?
Thank you in advance.

**Comment by tannerryan** [comment]
I don't seem to understand the issue you are encountering. May you please re-describe the issue and use GitHub's markdown formatting. Thanks!

**Comment by Agipa** [comment]
Hello! Sorry, let me make more clear. 1. I need a string representation of bitset, which was generated after inserting data into Bloom Filter. For example, 
`data := []byte("hello")
 r.Add(data)
fmt.Printf("%s in ring :: %t\n", data, r.Test(data))
fmt.Println(r.MarshalBinary())` (taken from your example)
the Output from Marshal.Binary() is 
`1 0 0 0 0 0 0 3 191 0 0 0 0 0 0 0 7 0 .....`
I can not understand , if Bloom Filter's output should be bitset containing only 0s and 1s, why your output contains the numbers except 0s and 1s?

**Comment by StrongJoshua** [comment]
I think the question here is why does your filter use an array called `bits` which contains bytes, instead of bits?

**Comment by tannerryan** [comment]
Sorry for the delay. Although the array is called `bits`, each entry actually holds 8 bits (1 byte). This is to stay efficient on memory. For instance, this is flipping the `n`th bit in the `t` entry to 1:
```go
r.bits[t] |= (1 << (n % 8))
```

If you need to extract the actual bits, you'll have to perform bitwise operations on each `bits` entry to generate 8 bits.
