### ISSUE TITLE
Module path should be "github.com/TheTannerRyan/ring", not "github.com/thetannerryan/ring"

### ISSUE THREAD

**Issue by KateGo520** [TheTannerRyan/ring#6]
## Background
Module path is inconsistent with go import path.
GO111MODULE=on, as [doc](https://godoc.org/github.com/TheTannerRyan/ring) said, import "github.com/TheTannerRyan/ring", then get this error:

```
go: finding module for package github.com/TheTannerRyan/ring
go: downloading github.com/TheTannerRyan/ring v1.1.1
go: found github.com/TheTannerRyan/ring in github.com/TheTannerRyan/ring v1.1.1
go: test1 imports
        github.com/TheTannerRyan/ring: github.com/TheTannerRyan/ring@v1.1.1: parsing go.mod:
        module declares its path as: github.com/thetannerryan/ring
                but was required as: github.com/TheTannerRyan/ring 
```

###  Fix the module path:
1) Rename the module path to "github.com/TheTannerRyan/ring": https://github.com/TheTannerRyan/ring/blob/master/go.mod#L1 
```
module github.com/TheTannerRyan/ring
go 1.12 
```
2) Consider reverting the `thetannerryan` -> `TheTannerRyan` rename.
2) Change the [doc](https://godoc.org/github.com/TheTannerRyan/ring) document to use `import "github.com/thetannerryan/ring"`.

**Comment by KateGo520** [comment]
@fastest963  Could you help me review this issue? Thx :p

**Comment by jameshartig** [comment]
@TheTannerRyan looks like in 6bf7b14618822768e1541f8d25d2dba79c27ae35 it was committed as lowercase but it needs to match the case on github. Either the `go.mod` should be changed or the github username should be lowercased and changed on github.

**Comment by KateGo520** [comment]
@tannerryan  I see the change of the name. Maybe you can also correct the import path in the [doc](https://godoc.org/github.com/tannerryan/ring).  Thank you for your reply!@fastest963

**Comment by tannerryan** [comment]
I am very sorry for the delay @fastest963 and @KateGo520. This has been on my bucket list. I have made the necessary changes in 3c08c223c7a07dba10f3dc36f819520816f2955a. Sorry again!

**Comment by jameshartig** [comment]
@KateGo520 can you confirm this is fixed and close this issue?
